volumes:
  mongo_volume:
  mosquitto_volume:

services:
  mongo-primary:
    image: mongo:7
    volumes:
      - mongo_volume:/data/db
    networks:
      - mongo
    ports:
      - '${MONGO_PORT:-27017}:27017'
    command: mongod --replSet rs0
    healthcheck:
      test: |
        mongosh --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5
    profiles:
      - 'deps-only'
      - 'dev'

  mosquitto:
    image: eclipse-mosquitto:2.0.10
    volumes:
      - ${PWD}/infra/mosquitto/etc/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_volume:/mosquitto/data
    ports:
      - 1883:1883
